### ISSUE TITLE
More config options for fatigue milestone or fatigue level modifiers

### ISSUE THREAD

**Issue by Darkmega18** [Su5eD/Somnia-Awoken#37]
_**Is your feature request related to a problem? Please describe.**_  
just a suggestion that makes potentially a bit more sense and allows more configurations.

_**Describe the solution you'd like**_  

Options to config program line by line different effects at different times, and whether they linger.
So like say:
"[Min-Max Fatigue level], [potion effect],[duration],[amp]"
on each line in an array. Then if a line has a duration setting set to 0 it'll remain until fatigue is lower than that level and is constantly like the final level of fatigue's super slowness. 

You could also therefore set up multiple next to one another and they'd work simultaneously. With say, a blindness at 70 being temporary for 5 seconds, but also at the same time at 70 you get a minor slowness or mining fatigues etc.

**Describe alternatives you've considered**  
there are no other alternatives.

**Comment by Su5eD** [comment]
Done. Side effect stages are now defined using a string array (had to go this way, because int arrays put each number on a new line, and int array arrays are not supported), where each string (line) represents one stage. This string is basically an int array, containing the min fatigue, max fatigue, potion ID, duration, and amplifier of a stage (in respective order). To make an effect permanent, set the duration to -1.

**Comment by Darkmega18** [comment]
roger that. look forward to trying it out and playing around with this. :D
