### ISSUE TITLE
Render Distance dramatically affects simulation speed

### ISSUE THREAD

**Issue by qdoyonnas** [Su5eD/Somnia-Awoken#83]
### Is your feature request related to a problem? Please describe.

Playing single-player I noticed that when I have render distance set to 24 chunks the sleep simulation speed is at around x2. Setting render distance to 2 chunks just before going to be boosts it to x14.

No idea how this performs for LAN/servers.

### Describe the solution you'd like

I do not know if a mod can do this, but would it make sense to have render distance be dropped to minimum when the player is in bed and returned to original value when getting out of bed?

### Additional context

Single-player
Rendering in config is set to False
Mob spawns are set to False

**Comment by Su5eD** [comment]
What minecraft version are you on? Older versions had both render & simulation distance settings in one config option.

**Comment by qdoyonnas** [comment]
Sorry I forgot to mention. Version 1.16

**Comment by Su5eD** [comment]
Yeah, in that case lowering the render distance will also lower the amount of simulated chunks, what boosts performance since there's less work to do.  
Disabling rendering in the mod config will remove any rendering load so only simulation affects performance. You can also check [this](https://github.com/Su5eD/Somnia-Awoken/discussions/81#discussioncomment-3455175) answer for tips to improve the tick multiplier.
